# Generated by Django 4.0.6 on 2022-08-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpireBasicTroops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empire.empirebasictroops')),
                ('EmpireCommanders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empire.empirecommanders')),
                ('EmpireHeroes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empire.empireheroes')),
                ('EmpireSingularTroops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empire.empiresingulartroops')),
                ('EmpireSpecialTroops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empire.empirespecialtroops')),
            ],
        ),
    ]
